//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmbulanceStatu
    {
        public int ID { get; set; }
        public string CarID { get; set; }
        public string AmbulanceName { get; set; }
        public string AmbulanceStatus { get; set; }
        public string DriverName { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    }
}
