//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class bedward
    {
        public int BedwID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string PatientName { get; set; }
        public string FatherName { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Physician { get; set; }
        public Nullable<System.DateTime> AssignFor { get; set; }
        public string RoomStatus { get; set; }
        public string Ward { get; set; }
        public string Room { get; set; }
        public string Cost { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
    }
}
