//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biochemistry
    {
        public int ID { get; set; }
        public string PatientID { get; set; }
        public string PatientName { get; set; }
        public string TechnitianName { get; set; }
        public string Physician { get; set; }
        public string Date { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public string Glucose_Fasting_R { get; set; }
        public string Two_Hr_Pg_Pp { get; set; }
        public string Blood_Urea { get; set; }
        public string Creatinine { get; set; }
        public string S_Cholesterol { get; set; }
        public byte[] Total_Protein { get; set; }
        public string Globwlin { get; set; }
        public string A_G_Ratio { get; set; }
        public string Game_Gt { get; set; }
    }
}
