//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blood
    {
        public int ID { get; set; }
        public string PatientID { get; set; }
        public string PatientName { get; set; }
        public string Sex { get; set; }
        public string Age { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Physician { get; set; }
        public string TechnitianName { get; set; }
        public string HAEMOGLOBIN { get; set; }
        public string TLC { get; set; }
        public string NEUTROPHILS { get; set; }
        public string LYMPHOCYTES { get; set; }
        public string EOSINOPHIL { get; set; }
        public string MONOCYTES { get; set; }
        public string BASOPHILS { get; set; }
        public string OTHERS { get; set; }
        public string ESR { get; set; }
        public string DiagnosisType { get; set; }
    }
}
