//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Charge
    {
        public int ID { get; set; }
        public string ServiceName { get; set; }
        public string ChargeIncludeTax { get; set; }
        public string TaxID { get; set; }
        public Nullable<int> AmountOfCharge { get; set; }
        public Nullable<int> Discount { get; set; }
    }
}
