//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosisOrder
    {
        public int ID { get; set; }
        public string PatientID { get; set; }
        public string PatientName { get; set; }
        public string PhysicianName { get; set; }
        public string StaffID { get; set; }
        public string Date { get; set; }
        public string Biochemistry { get; set; }
        public string Stool { get; set; }
        public string Blood { get; set; }
        public string Colonoscopy { get; set; }
        public string Urine { get; set; }
        public string Gastroscopy { get; set; }
        public string Xray { get; set; }
        public string Sonography { get; set; }
        public string ECG { get; set; }
        public string Ultrasound { get; set; }
        public string OtherTest { get; set; }
    }
}
