//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class drugitem
    {
        public int ID { get; set; }
        public string DrugGroup { get; set; }
        public string DrugName { get; set; }
        public Nullable<int> DrugQuantity { get; set; }
        public string DrugRefills { get; set; }
        public string DrugDosage { get; set; }
        public string DrugApplication { get; set; }
        public string DrugFrequency { get; set; }
        public string DrugPeriod { get; set; }
    }
}
