//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugDescription
    {
        public int DrugId { get; set; }
        public string DrugName { get; set; }
        public string DrugType { get; set; }
        public string Prescribed { get; set; }
        public string CommonSide { get; set; }
        public string PossibleSide { get; set; }
        public string Interaction { get; set; }
        public string Warning { get; set; }
        public string Alternatives { get; set; }
        public string Brand { get; set; }
    }
}
