//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecgelemntadd
    {
        public int ECGelemntaddId { get; set; }
        public string InvestigationType { get; set; }
        public string InvestigationEntity { get; set; }
        public string SubEntity { get; set; }
        public string Report { get; set; }
        public Nullable<long> Coast { get; set; }
    }
}
