//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirstDiagnosi
    {
        public int ID { get; set; }
        public string PatientID { get; set; }
        public string PatientName { get; set; }
        public string Sex { get; set; }
        public string Age { get; set; }
        public string Temparture { get; set; }
        public string BP_SID_ { get; set; }
        public string PulseRate { get; set; }
        public string HeartBeet { get; set; }
        public string RespirotoryRate { get; set; }
        public string Spo2 { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string HeadCircumfrance { get; set; }
        public string WaistCircumfrance { get; set; }
        public string RBS { get; set; }
        public string FBS { get; set; }
        public string Ht_Lt { get; set; }
        public string MUAC { get; set; }
        public string Wt_Age { get; set; }
        public string Wt_Ht { get; set; }
        public string BP_for_Age_and_Ht { get; set; }
        public string BMI { get; set; }
        public string BMI_Age { get; set; }
        public string BUAC_Age { get; set; }
        public string HC_Age { get; set; }
    }
}
