//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class foPatient
    {
        public foPatient()
        {
            this.foDoctorAssignments = new HashSet<foDoctorAssignment>();
            this.foVitals = new HashSet<foVital>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Sex { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public int MaternalState { get; set; }
        public Nullable<int> RegistrationMechanismId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> NurseId { get; set; }
        public Nullable<int> ChargeTypeId { get; set; }
        public string FullName { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string SubCity { get; set; }
        public string HNo { get; set; }
        public string PassPortId { get; set; }
        public string Nationality { get; set; }
        public string Kebele { get; set; }
        public string Wereda { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual ICollection<foDoctorAssignment> foDoctorAssignments { get; set; }
        public virtual foNewPatient foNewPatient { get; set; }
        public virtual FoPastMedicalHistory FoPastMedicalHistory { get; set; }
        public virtual ICollection<foVital> foVitals { get; set; }
    }
}
