//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoPastMedicalHistory1
    {
        public int PatientId { get; set; }
        public string Ccompliment { get; set; }
        public string PIllness { get; set; }
        public string EarlyDevelopment { get; set; }
        public string Education { get; set; }
        public string SocialActivities { get; set; }
        public string WorkRecord { get; set; }
        public string Environment { get; set; }
        public string Habits { get; set; }
        public string MentalStatus { get; set; }
        public string Other { get; set; }
        public string DifDiagnosis { get; set; }
        public string Assesment { get; set; }
        public bool MentalHistory { get; set; }
        public bool PregnancyHistory { get; set; }
        public bool HeartDisease { get; set; }
        public bool Hypertension { get; set; }
        public bool Dyslipidemia { get; set; }
        public bool Diabetes { get; set; }
        public bool Cancer { get; set; }
        public bool Anthemia { get; set; }
        public bool Pastillness { get; set; }
        public bool AdmissionHistory { get; set; }
        public string MentalHistoryRemark { get; set; }
        public string PregnancyHistoryRemark { get; set; }
        public string HeartDiseaseRemark { get; set; }
        public string HypertensionRemark { get; set; }
        public string DyslipidemiaRemark { get; set; }
        public string DiabetesRemark { get; set; }
        public string CancerRemark { get; set; }
        public string AnthemiaRemark { get; set; }
        public string PastillnessRemark { get; set; }
        public string AdmissionHistoryRemark { get; set; }
        public bool FatherandMother { get; set; }
        public string FatherandMotherRemark { get; set; }
        public bool Siblings { get; set; }
        public string SiblingsRemark { get; set; }
        public bool Familydisease { get; set; }
        public bool HEENT { get; set; }
        public string HEENTRemark { get; set; }
        public bool Glands { get; set; }
        public string GlandsRemark { get; set; }
        public bool Respiratory { get; set; }
        public string RespiratoryRemark { get; set; }
        public bool CNS { get; set; }
        public string CNSRemark { get; set; }
        public bool Cardiovascular { get; set; }
        public string CardiovascularRemark { get; set; }
        public bool Gastrointestinal { get; set; }
        public string GastrointestinalRemark { get; set; }
        public bool Genitourinary { get; set; }
        public string GenitourinaryRemark { get; set; }
        public string CurrentModification { get; set; }
        public string Allergies { get; set; }
        public string FamilydiseaseRemark { get; set; }
        public bool FamilyOther { get; set; }
        public string FamilyOtherRemark { get; set; }
        public string OtherSocialHistoryRemark { get; set; }
        public bool Integumentary { get; set; }
        public string IntegumentaryRemark { get; set; }
        public bool Allergy { get; set; }
        public string AllergyRemark { get; set; }
        public bool Locomotors { get; set; }
        public string LocomotorsRemark { get; set; }
        public bool ReviewSysOther { get; set; }
        public string ReviewSysOtherRemark { get; set; }
        public bool GeneralAppearance { get; set; }
        public string GeneralAppearanceRemark { get; set; }
        public bool RespiratorySystem { get; set; }
        public string RespiratorySystemRemark { get; set; }
        public bool NervousSystem { get; set; }
        public string NervousSystemRemark { get; set; }
        public bool CentralSystem { get; set; }
        public string CentralSystemRemark { get; set; }
        public bool Motor { get; set; }
        public string MotorRemark { get; set; }
        public bool Sensory { get; set; }
        public string SensoryRemark { get; set; }
        public bool Reflex { get; set; }
        public string ReflexRemark { get; set; }
        public bool GeneralOther { get; set; }
        public string GeneralOtherRemark { get; set; }
        public string bp1 { get; set; }
        public string bp2 { get; set; }
        public string bp3 { get; set; }
        public string bp4 { get; set; }
        public string bp5 { get; set; }
        public string bp6 { get; set; }
        public string bp7 { get; set; }
        public string bp8 { get; set; }
        public string bp9 { get; set; }
        public string bp10 { get; set; }
        public string bp11 { get; set; }
        public string bp12 { get; set; }
        public string tp1 { get; set; }
        public string tp2 { get; set; }
        public string tp3 { get; set; }
        public string tp4 { get; set; }
        public string tp5 { get; set; }
        public string tp6 { get; set; }
        public string p { get; set; }
        public string rr { get; set; }
        public string brpm { get; set; }
        public string wt { get; set; }
        public string wsf { get; set; }
        public string hsf { get; set; }
        public string bmi { get; set; }
        public string vr { get; set; }
        public string vl { get; set; }
    
        public virtual foPatient foPatient { get; set; }
    }
}
