//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class foVital
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public Nullable<double> Temprature { get; set; }
        public Nullable<double> BPSID { get; set; }
        public Nullable<double> BPSIDDividende { get; set; }
        public Nullable<double> PulseRate { get; set; }
        public Nullable<double> RespirotoryRate { get; set; }
        public Nullable<double> Spo2 { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> HeadCircumfrance { get; set; }
        public Nullable<double> WaistCircumfrance { get; set; }
        public Nullable<double> RBS { get; set; }
        public Nullable<double> FBS { get; set; }
        public Nullable<double> HtLt { get; set; }
        public Nullable<double> MUAC { get; set; }
        public Nullable<double> WtAge { get; set; }
        public Nullable<double> wtHeight { get; set; }
        public Nullable<double> BMIAge { get; set; }
        public Nullable<double> BUACAge { get; set; }
        public Nullable<double> HCAge { get; set; }
        public Nullable<double> BPAgeAndHt { get; set; }
    
        public virtual foPatient foPatient { get; set; }
    }
}
