//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hamatology
    {
        public int ID { get; set; }
        public string PatientID { get; set; }
        public string PatientName { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public string Physician { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string WBC { get; set; }
        public string DiffN { get; set; }
        public string HGB { get; set; }
        public string HCT { get; set; }
        public string ESR { get; set; }
        public string RBC { get; set; }
        public string Platlate { get; set; }
        public string BloodgroupsRh { get; set; }
        public string BloodFilm { get; set; }
        public string DyagnosisType { get; set; }
    }
}
