//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISubentity
    {
        public int ISID { get; set; }
        public string Subentitiese { get; set; }
        public Nullable<int> Gener4 { get; set; }
        public Nullable<int> IEntitiyId { get; set; }
    
        public virtual IEntity IEntity { get; set; }
    }
}
