//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ID { get; set; }
        public string MeasurmentUnit { get; set; }
        public string ItemCatagory { get; set; }
        public string ItemStatus { get; set; }
        public string Itemquantity { get; set; }
        public string Remarks { get; set; }
    }
}
