//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Labelemntadd
    {
        public int Labitemaddid { get; set; }
        public string InvestigationType { get; set; }
        public string InvestigationEntity { get; set; }
        public string SubEntity { get; set; }
        public string Unit { get; set; }
        public string Lowerbound { get; set; }
        public string Upperbound { get; set; }
        public string Formula { get; set; }
        public string UpperboundChildren { get; set; }
        public string LowerboundChildren { get; set; }
        public string TestType { get; set; }
        public string defval { get; set; }
        public string UboundmC { get; set; }
        public string lboundfC { get; set; }
        public string Result { get; set; }
        public Nullable<long> Coast { get; set; }
    }
}
