//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Labratoryresult
    {
        public int LabID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string PatientName { get; set; }
        public string FatherName { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PhysicianName { get; set; }
        public string TechnitianName { get; set; }
        public string InvestigationType { get; set; }
        public string InvestigationEntity { get; set; }
        public string SubEntity { get; set; }
        public string Result { get; set; }
        public string Unit { get; set; }
        public string NormalRange { get; set; }
        public string InvestigationStatus { get; set; }
        public string Description { get; set; }
        public string LowerBound { get; set; }
        public string UpperBound { get; set; }
    }
}
