//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Labtest
    {
        public Labtest()
        {
            this.Labtest1 = new HashSet<Labtest>();
        }
    
        public int LabTestID { get; set; }
        public string TestType { get; set; }
        public string TestEntity { get; set; }
        public string SubEntity { get; set; }
        public Nullable<int> MinimumRange { get; set; }
        public Nullable<int> MaximumRange { get; set; }
        public string Unit { get; set; }
        public Nullable<int> ChildrenUpper { get; set; }
        public Nullable<int> Childrenlower { get; set; }
        public Nullable<int> Maleupper { get; set; }
        public Nullable<int> Malelower { get; set; }
        public Nullable<int> Femaleupper { get; set; }
        public Nullable<int> Femalelower { get; set; }
        public Nullable<int> Childs { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Labtest> Labtest1 { get; set; }
        public virtual Labtest Labtest2 { get; set; }
    }
}
