//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicalcerteficateee
    {
        public int medcertefiID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string PatientName { get; set; }
        public string FatherName { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PhysicianName { get; set; }
        public string DiseaseType { get; set; }
        public Nullable<System.DateTime> MedicineStartFrom { get; set; }
        public Nullable<System.DateTime> UpTo { get; set; }
        public string Reason { get; set; }
        public string ApprovedBy { get; set; }
    }
}
