//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutpaitentActivity
    {
        public int ID { get; set; }
        public string PatientName { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> DateofVisit { get; set; }
        public string TypeofMedicine { get; set; }
        public string Typeof_investigationBefore___Type_of_Investigation_Before___Type_of_Investigation_Before___ { get; set; }
        public string PreviousVisitDate { get; set; }
    }
}
