//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientRegistration
    {
        public int paitentID { get; set; }
        public string Status { get; set; }
        public string Name { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Sex { get; set; }
        public string Date { get; set; }
        public string RegistrationMechanism { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Age { get; set; }
        public string MaternalState { get; set; }
        public string Time { get; set; }
        public string AssignedDepartment { get; set; }
        public string AssignedNurse { get; set; }
        public string ChargeType { get; set; }
    }
}
