//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perscription
    {
        public int perscriptionID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string PatientName { get; set; }
        public string FatherName { get; set; }
        public string Sex { get; set; }
        public string Age { get; set; }
        public string Date { get; set; }
        public string PhysicianName { get; set; }
        public string MedicineType { get; set; }
        public string MedicineName { get; set; }
        public string Frequancy { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> UpTo { get; set; }
        public string Dosage { get; set; }
    }
}
