//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Possition
    {
        public int ID { get; set; }
        public string Department { get; set; }
        public string Branch { get; set; }
        public string PossitionName { get; set; }
        public string Remarks { get; set; }
    }
}
