//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string Sex { get; set; }
        public string AssignDepartment { get; set; }
        public string Physician { get; set; }
        public string ReserverName { get; set; }
        public string TimeofCall { get; set; }
        public string ReservedDate { get; set; }
        public string ReservedTime { get; set; }
        public string Remaks { get; set; }
    }
}
