//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomStatu
    {
        public int ID { get; set; }
        public string RoomID { get; set; }
        public string RoomName { get; set; }
        public string RoomState { get; set; }
        public string Occupied { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    }
}
