//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomService
    {
        public int ID { get; set; }
        public string BlockName { get; set; }
        public string BlockNumber { get; set; }
        public string FloorNumber { get; set; }
        public string RoomNumber { get; set; }
        public string RoomStatus { get; set; }
        public string ProcterName { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string ItemID { get; set; }
    }
}
