//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class secUser
    {
        public secUser()
        {
            this.secPermissions = new HashSet<secPermission>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string PassWord { get; set; }
        public bool Terminated { get; set; }
        public bool Locked { get; set; }
    
        public virtual ICollection<secPermission> secPermissions { get; set; }
    }
}
