//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stool
    {
        public int ID { get; set; }
        public string PatientID { get; set; }
        public string PatientName { get; set; }
        public string Sex { get; set; }
        public string Age { get; set; }
        public string TechnitianName { get; set; }
        public string Physician { get; set; }
        public string Date { get; set; }
        public string Color { get; set; }
        public string Consistency { get; set; }
        public string Mucus { get; set; }
        public string Blood { get; set; }
        public string Wbc_Hpf { get; set; }
        public string Rbc_Hpf { get; set; }
        public string Mecrophages { get; set; }
        public string Trophozoite { get; set; }
        public string P_Ova { get; set; }
    }
}
